### ISSUE TITLE
Hosting your deb

### ISSUE THREAD

**Issue by if0x** [awesomebing1/iOS-sbutils#1]
Not a real issue just kind questions if I'm allowed to host your deb file on my repo as I want to use it on public stuff. Hope for an answer soon thanks :)

**Comment by spotlightishere** [comment]
Go for it; however, since this is a fork from @bored-engineer, you might want to add attribution somewhere (say, the description) as the original repo has no license, bringing it to the ever standing legal gray area of "is this public domain or closed source?"

Otherwise, yeah, and thank you for asking :P
